### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by farnaf** [Alexander-Qinn/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
  - please format all terminal commands as code (e.g., $ ssh cs15lwi22zz@ieng6.ucsd.edu, etc)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
  - please user markdown headers for the different section titles
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - please include what you tried in lab 1: Use what you’ve learned to come up with the most pleasant process you can for making a local edit to WhereAmI.java, then copying it to the remote server and running it.
- [x] Text is formatted in a way that was easy for grader to read
  - for Step 3. Trying Some Commands, please include the commands your tried / description of what they're used for rather than using a screenshot of lab 1
  - the image right before Step 6. Optimize Remote Running doesn't load for me

Additional comments from your grader:
nice job 😃
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by farnaf** [comment]
Thanks for submitting a regrade request!

The second to last requirement is not complete yet. What we're looking for is the command you came up with that once typed in your local terminal, the java program compiles/runs on the server (the computer you access when you ssh with your 15L account).

To do the above task the long way, we can (1) use scp to copy the java file over to the server (2) ssh into 15L account (3) compile the copied java file (4) run it. The goal of the last step is to come up with an optimized version of these 4 steps.

**Comment by Alexander-Qinn** [comment]
So am I able to resubmit the lab report in an attempt to get full credit or no?

**Comment by farnaf** [comment]
Yes, we'll re-open the window for regrade requests next week (just for lab report 1), and you can resubmit(:
